### ISSUE TITLE
Code is not Composer friendly

### ISSUE THREAD

**Issue by wpscholar** [zamoose/themehookalliance#31]
A Composer dependency shouldn't automatically run any code.  The autoloaded `tha-theme-hooks.php` file calls `add_theme_support()` and `add_filter()`, which have not been setup if calling the Composer `autoload.php` file at the top of a `wp-config.php` file.  The end result of this is a fatal error and inability to use this library with WordPress projects that utilize the Composer autoload functionality.

There are two possible solutions to this issue: 
1. Remove the `autoload` property from the `composer.json` file.  Loading the code would then require an include.
2. Wrap the `add_theme_support()` and `add_filter()` functions in a class that could be instantiated later.  The class constructor would need to add a callback on the `after_setup_theme` hook which would then run the setup code.

**Comment by teohhanhui** [comment]
The code is still not Composer friendly if the theme doesn't support all hooks, as `add_theme_support` is inexplicably being called in the include file (tha-theme-hooks.php)...

**Comment by teohhanhui** [comment]
I'd also like to note that since you opted to remove autoloading, it means that the path to the vendor directory (e.g. `/vendor/themehookalliance/`) needs to be hardcoded in the theme's functions.php.

I think that's undesirable.

**Comment by wpscholar** [comment]
@teohhanhui,

A Composer library that is autoloaded should not run any code.  Since this repo cannot be autoloaded as-is because it runs code, it can't be treated as a traditional Composer library.  Ideally, the code should be adjusted such that it can be autoloaded and then called when needed without the need for an include or require.  Until then, removing autoloading from the composer.json file prevents it from crashing sites.

So, you are correct.  This should be revisited.  The best way to fix this will require some code restructuring, which at the time wasn't likely to be accepted.
