### ISSUE TITLE
No entry content "inside" hook or after endwhile hook

### ISSUE THREAD

**Issue by robneu** [zamoose/themehookalliance#40]
After using THA for a while, there are two hooks that I think should really be added. Right now there's no hook for within the actual "content" area of an entry. This makes hooking the the post content along with other post elements a little tricky as it needs to be done with priority juggling and choosing whether or not the content goes on the top or bottom.

The other missing hook is an after endwhile hook. Sometimes you need to hook content after the 
`<?php while ( have_posts() ) : the_post(); ?>` part of a loop but before the `endif` check to see if the loop actually contains post data.

I know there are some old proposals to add more content-specific hooks and things like that, but so far I think these are the only two that can actually cause a problem because they are omitted. Related to #7 and #9

**Comment by richardtape** [comment]
:+1: +1 for this, too. We're starting to come across issues where content order juggling is unmanageable and an extra couple hooks as @robneu mentions would be an immediate resolution for this.
